### PR TITLE
feat(crossplane): Use default poll and sync intervals

### PR DESCRIPTION
**Pull request by gmykhailiuta**
> The poll option determines how often the provider will compare the desired Workspace configuration with the actual deployed resources (terraform plan) and reconcile any differences (terraform apply). The default value is 10m. Shorter poll intervals increase the load on the provider by reconciling existing Workspaces more often to allow for faster reconciliation of differences, but this can cause the provider to take longer to process new Workspace objects that are created. Longer poll intervals will reduce the load on the provider by reconciling existing Workspaces less often, taking a longer time to identify and reconcile differences, but also shortening the amount of time required for the provider to respond to new Workspaces.

For `--sync` parameter the best explanation I could find is the code: https://github.com/crossplane/upjet-provider-template/blob/ff852aca552ccc12e18c11e41752bec3b2f1f64a/cmd/provider/main.go#L41C3-L41C13.

We have increased these options to lower the load on crossplane but I've noticed that it sometimes is very challenging to eliminate drift.

### CODE REVIEW

**Comment by dmytro-golovchenko-luminartech** [comment]
what is default value and what would be an implication of this change?

**Review by ssbagwe — DISMISSED** [review]

**Comment by gmykhailiuta** [comment]
@dmytro-golovchenko-luminartech, added more info to the description.

**Comment by dmytro-golovchenko-luminartech** [comment]
> @dmytro-golovchenko-luminartech, added more info to the description.

Does it mean that 10 minutes is the maximum delay after which we will be able to restart sync job on the new worker and have ipsec tunnel bound to it?

**Review by dmytro-golovchenko-luminartech — APPROVED** [review]

**Comment by gmykhailiuta** [comment]
Technically yes. This PR should make Crossplane check more often that we have correct IAM policies attached to the role.

**Pull request merged**
